DROP TABLE IF EXISTS `one_provider`;
CREATE TABLE `one_provider` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '供货商名字',
  `contact` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '联系人',
  `phone` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '联系号码',
  `address` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '地址',
  `qq` VARCHAR(15) NOT NULL DEFAULT '' COMMENT 'QQ号码',
  PRIMARY KEY  (`id`)
) ENGINE=MYISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='供货商表';